# Config Management
unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded."

# -- Prefix substitution
set -g prefix M-a
bind M-a send-prefix

# -- Scroll limit
set -g history-limit 100000

## -- Rename Off
#set -g allow-rename off

# -- Status bar left and right lenght
set -g status-left-length 60
set -g status-right-length 120


# -- Auto-destroy only tmp-* sessions when they have no attached clients
set-hook -g client-detached 'run-shell "s=#{session_name}; case \"$s\" in tmp-*) tmux set -t \"$s\" destroy-unattached on ;; esac"'

# -- Search Mode VI
set-window-option -g mode-keys vi

# -- Copy mode VI
setw -g mode-keys vi

# -- Join Windows
bind-key e command-prompt -p "join pane from:" "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:" "join-pane -t '%%'"

# -- Window next and previous
bind -n M-x next-window
bind -n M-z previous-window

# Switch Windows
bind-key 0 select-window -t 0
bind-key 1 select-window -t 1
bind-key 2 select-window -t 2
bind-key 3 select-window -t 3
bind-key 4 select-window -t 4
bind-key 5 select-window -t 5
bind-key 6 select-window -t 6
bind-key 7 select-window -t 7
bind-key 8 select-window -t 8
bind-key 9 select-window -t 9

# Numbering & Naming
set -g base-index 1
setw -g pane-base-index 1
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Windows
unbind W
bind-key W command-prompt -p "Window name:" "new-window -n '%%'" # New Window
bind-key t command-prompt -p "New name:" "rename-window '%%'"   # Rename Window

# Panes
bind-key P command-prompt -p "Rename pane:" "select-pane -T '%%'"
bind a split-window -v -c "#{pane_current_path}"
bind z split-window -h -c "#{pane_current_path}"
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r -n M-Left  resize-pane -L 5
bind -r -n M-Right resize-pane -R 5
bind -r -n M-Up    resize-pane -U 2
bind -r -n M-Down  resize-pane -D 2

# -- allow mouse
set -g mouse on

